config/routes.rb
Rosetta::Engine.routes.draw do
  root to: "locales#index"

  resource :default_locale, only: %i[new create]

  resources :locales do
    scope module: :locales do
      resources :translations, only: :index
      resources :deploys, only: :create

      namespace :translations do
        resources :missing, only: :index
      end
    end
  end

  resources :text_entries do
    resource :translation, only: %i[edit update]
  end
end

app/models/rosetta/application_record.rb
module Rosetta
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/rosetta/locale.rb
module Rosetta
  class Locale < ApplicationRecord
    class_attribute :registered_classes_for_translations, default: []

    CODE_FORMAT = /\A[a-zA-Z]+(-[a-zA-Z]+)?\z/

    validates :name, :code, presence: true
    validates :code, uniqueness: true
    validates :code, format: { with: CODE_FORMAT, message: "must only contain letters separated by an optional dash" }

    has_many :text_entries, dependent: :destroy
    after_create_commit :notify_translated_models
    has_many :pluralization_rules, dependent: :destroy

    class << self
      def available_locales
        all
      end

      def build_as_default(params)
        new(params.merge(default: true))
      end

      def default_locale
        @default_locale ||= find_by(default: true)
      end

      def default_locale=(locale)
        @default_locale = locale
      end
      def register_class_for_translation(klass)
        registered_classes_for_translations << klass
      end
    end

    def notify_translated_models
      registered_classes_for_translations.each { |klass| klass.translated_in(self) }
    end
  end
end

app/models/rosetta/pluralization_rule.rb
module Rosetta
  class PluralizationRule < ApplicationRecord
    OPERATORS = {
      less_than_or_equal_to: Pluralization::Operators::LessThanOrEqualTo,
      less_than: Pluralization::Operators::LessThan,
      equal_to: Pluralization::Operators::EqualTo,
      greater_than_or_equal_to: Pluralization::Operators::GreaterThanOrEqualTo,
      greater_than: Pluralization::Operators::GreaterThan
    }.with_indifferent_access

    belongs_to :locale

    validates :name, :operator, :threshold, presence: true
    validates :threshold, numericality: { greater_than_or_equal_to: 0 }
    validates :operator, inclusion: { in: OPERATORS.keys }

    def activated?(test_value)
      OPERATORS[operator].new(value: test_value, threshold: threshold).check
    end
  end
end

app/models/rosetta/text_entry.rb
module Rosetta
  class TextEntry < ApplicationRecord
    include Translated

    translate_in_all_locales

    belongs_to :locale

    def self.create_later(content)
      AutodiscoveryJob.perform_later(content)
    end

    def purge
      destroy
    rescue ActiveRecord::InvalidForeignKey
    end

    def purge_later
      PurgeJob.perform_later(self)
    end
  end
end

app/models/rosetta/translation.rb
module Rosetta
  class Translation < ApplicationRecord
    belongs_to :target_locale, class_name: "Rosetta::Locale"
    belongs_to :from, class_name: "Rosetta::TextEntry"
    belongs_to :to, class_name: "Rosetta::TextEntry"

    after_destroy_commit :purge_orphaned_text_entries_later

    private

    def purge_orphaned_text_entries_later
      to.purge_later
    end
  end
end

app/controllers/concerns/rosetta/locale_scoped.rb
module Rosetta
  module LocaleScoped
    extend ActiveSupport::Concern

    included do
      before_action :set_locale
    end

    private

    def set_locale(&action)
      @locale = Locale.find(params[:locale_id])
    end
  end
end

app/controllers/rosetta/application_controller.rb
module Rosetta
  class ApplicationController < Rosetta.config.parent_controller_class.constantize
    include Pagy::Backend
  end
end

app/controllers/rosetta/default_locales_controller.rb
module Rosetta
  class DefaultLocalesController < ApplicationController
    before_action :ensure_configuration_needed

    def new
        @locale = Locale.new
    end

    def create
      @locale = Locale.build_as_default(locale_params)

      if @locale.save
        redirect_to locales_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    private

    def ensure_configuration_needed
      redirect_to root_path if Locale.default_locale
    end

    def locale_params
      params.require(:locale).permit(:name, :code)
    end
  end
end

app/controllers/rosetta/locales/deploys_controller.rb
module Rosetta
  class Locales::DeploysController < ApplicationController
    include LocaleScoped

    def create
      @locale.touch
      flash[:notice] = "#{@locale.name} changes have been deployed."

      redirect_back(fallback_location: locale_translations_path(@locale))
    end
  end
end

app/controllers/rosetta/locales/translation_keys_controller.rb
module Rosetta
  class Locales::TranslationKeysController < ApplicationController
    before_action :set_locale

    def index
      @pagy, @translation_keys = pagy(TranslationKey
        .includes(:translations)
        .joins("LEFT JOIN rosetta_translations ON rosetta_translations.translation_key_id = rosetta_translation_keys.id AND rosetta_translations.locale_id = #{@locale.id}")
        .order(created_at: :desc)
      )
    end

    private

    def set_locale
      @locale = Locale.find(params[:locale_id])
    end
  end
end

app/controllers/rosetta/locales/translations/missing_controller.rb
module Rosetta
  class Locales::Translations::MissingController < Locales::TranslationsController
    private

    def scope
      Locale.default_locale.text_entries.missing_translation(@locale)
    end
  end
end

app/controllers/rosetta/locales/translations_controller.rb
module Rosetta
  class Locales::TranslationsController < ApplicationController
    include LocaleScoped

    def index
      @pagy, @text_entries = pagy(scope)

      render "rosetta/locales/translations/index"
    end

    private

    def scope
      TextEntry.with_translated_version(@locale).where(locale: Locale.default_locale)
    end
  end
end

app/controllers/rosetta/locales_controller.rb
module Rosetta
  class LocalesController < ApplicationController
    before_action :ensure_default_locale_exists, only: :index

    def index
      @locales = Locale.order(default: :desc)
    end

    def new
      @locale = Locale.new
    end

    def create
      @locale = Locale.new(locale_params)

      if @locale.save
        redirect_to locales_path
      else
        render turbo_stream: turbo_stream.update(
          :dialog_content,
          partial: "form",
          locals: { locale: @locale }
        )
      end
    end

    private

    def ensure_default_locale_exists
      redirect_to new_default_locale_path unless Locale.default_locale
    end

    def locale_params
      params.require(:locale).permit(:name, :code)
    end
  end
end

app/controllers/rosetta/translations_controller.rb
module Rosetta
  class TranslationsController < ApplicationController
    include LocaleScoped

    before_action :set_text_entry

    def edit
    end

    def update
      @text_entry.update(text_entry_params)

      render partial: "rosetta/text_entries/text_entry_with_translation", locals: { text_entry: @text_entry }
    end

    private

    def set_text_entry
      @text_entry = TextEntry.find(params[:text_entry_id])
    end

    def text_entry_params
      params.require(:text_entry).permit(:"content_#{@locale.code}")
    end
  end
end

app/helpers/rosetta/application_helper.rb
module Rosetta
  module ApplicationHelper
    include Pagy::Frontend
    include DialogHelper
    include NavigationHelper
  end
end

app/helpers/rosetta/dialog_helper.rb
module Rosetta
  module DialogHelper
    def within_modal(&block)
      turbo_frame_tag :dialog_content, &block
    end

    def modal_title(title)
      tag.h1(title, class: "hidden", data: { dialog_target: "titleSource" })
    end
  end
end

app/helpers/rosetta/navigation_helper.rb
module Rosetta
  module NavigationHelper
    def tab_link_to(name = nil, options = nil, html_options = nil, &block)
      is_current_page = current_page?(block_given? ? name : options)

      css_classes = class_names(
        "flex group whitespace-nowrap border-b-2 px-1 py-4 text-sm font-medium",
        "active border-indigo-500 text-indigo-600": is_current_page,
        "border-transparent text-gray-500 hover:border-gray-200 hover:text-gray-700": !is_current_page
      )

      html_options = { class: css_classes, aria: { current: "page" } }

      if block_given?
        link_to(name, html_options, &block)
      else
        link_to(name, options, html_options)
      end
    end
  end
end

app/helpers/rosetta/translation_helper.rb
module Rosetta
  module TranslationHelper
    def _(key, locale: Rosetta.locale)
      return key if Rosetta.locale.default?

      Rosetta.translate(key, locale: locale) || key
    end
  end
end

app/views/layouts/rosetta/_dialog.html.erb
<dialog class="absolute max-w-4xl w-full mx-auto p-12 top-4 left-0 m-0 h-full bg-transparent" data-dialog-target="dialog" data-action="close->dialog#resetContent click->dialog#safeClose">
  <div class="bg-white shadow ring-1 ring-black ring-opacity-5 max-w-xl mt-4 mx-auto rounded-lg overflow-hidden w-full" data-dialog-target="content">
    <div class="flex justify-between bg-gray-50 py-4 px-6 text-gray-900 font-semibold border-b border-gray-300">
      <h4 data-dialog-target="title"></h4>

      <button type="button" class="rounded-md text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" data-action="dialog#close">
        <span class="sr-only">Close</span>
        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>

    <div class="p-4">
      <%= turbo_frame_tag "dialog_content", data: { dialog_target: "turboFrame" } do %>
        <div class="flex justify-around py-12">
          <svg class="animate-spin h-5 w-5 text-black" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
        </div>
      <% end %>
    </div>
  </div>
</dialog>

app/views/layouts/rosetta/_flashes.html.erb
<% if flash[:notice] %>
  <div class="bg-green-50 border-b border-green-100 text-green-800">
    <div class="mx-auto max-w-4xl p-4 sm:px-6 lg:px-8">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

app/views/layouts/rosetta/_navbar.html.erb
<nav class="border-b border-gray-200 bg-white">
  <div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
    <div class="flex items-center">
      <%= link_to "Rosetta", root_path, class: "text-xl font-bold" %>
    </div>
  </div>
</nav>

app/views/layouts/rosetta/application.html.erb
<!DOCTYPE html>
<html class="h-full">
<head>
  <title>Rosetta</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%= stylesheet_link_tag    "rosetta/application", media: "all" %>
  <%= javascript_include_tag "rosetta/application", defer: true %>
</head>
<body class="h-full" data-controller="dialog">
  <div class="min-h-full">
    <%= render "layouts/rosetta/navbar" %>
    <%= render "layouts/rosetta/flashes" %>

    <main class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-10">
      <%= yield %>
    </main>
  </div>

  <%= render "layouts/rosetta/dialog" %>
</body>
</html>

app/views/rosetta/default_locales/new.html.erb
<h1 class="text-3xl font-bold">
  Setup default locale
</h1>

<div class="rounded-md bg-blue-50 p-4 mt-8">
  <div class="flex">
    <div class="flex-shrink-0">
      <svg class="h-5 w-5 text-blue-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a.75.75 0 000 1.5h.253a.25.25 0 01.244.304l-.459 2.066A1.75 1.75 0 0010.747 15H11a.75.75 0 000-1.5h-.253a.25.25 0 01-.244-.304l.459-2.066A1.75 1.75 0 009.253 9H9z" clip-rule="evenodd" />
      </svg>
    </div>
    <div class="ml-3">
      <h3 class="font-medium text-blue-800">Rosetta needs a default locale set up to work properly</h3>

      <p class="text-sm text-blue-700 mt-2">
        The default locale is the locale the codebase is written in. It is not supposed to change in the future, though it can be edited if needed later on.
      </p>
    </div>
  </div>
</div>

<%= form_with model: @locale, url: default_locale_path, class: "grid gap-2 mt-8" do |f| %>
  <% if @locale.errors[:code].any? %>
    <div class="rounded-md bg-red-50 p-4">
      <div class="flex">
        <div class="flex-shrink-0">
          <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
          </svg>
        </div>
        <div class="ml-3">
          <div class="text-sm text-red-700">
            Please check the format of your locale code, and make sure it does not already exist.
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div>
    <%= f.label :name, class: "label" %>
    <%= f.text_field :name, placeholder: "E.g. English", class: "input max-w-xs", required: true %>
  </div>

  <div>
    <%= f.label :code, class: "label" %>
    <%= f.text_field :code, placeholder: "E.g. en", class: "input max-w-28", required: true  %>
    <p class="mt-1 text-sm leading-6 text-gray-600">
      Downcase letters followed by an optional region specifier in uppercase letters, separated by a dash. E.g. <span class="badge">fr</span> or <span class="badge">en-GB</span>.
    </p>
  </div>

  <%= f.submit "Setup default locale", class: "btn btn-primary mt-2" %>
<% end %>

app/views/rosetta/locales/_form.html.erb
<%= form_with model: locale, class: "grid gap-2", data: { turbo_frame: "_top" } do |f| %>
  <% if @locale.errors[:code].any? %>
    <div class="rounded-md bg-red-50 p-4">
      <div class="flex">
        <div class="flex-shrink-0">
          <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
          </svg>
        </div>
        <div class="ml-3">
          <div class="text-sm text-red-700">
            Please check the format of your locale code, and make sure it does not already exist.
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div>
    <%= f.label :name, class: "label" %>
    <%= f.text_field :name, placeholder: "E.g. French", class: "input max-w-xs", required: true %>
  </div>

  <div>
    <%= f.label :code, class: "label" %>
    <%= f.text_field :code, placeholder: "E.g. fr, en-GB", class: "input max-w-28", required: true  %>
    <p class="mt-1 text-sm leading-6 text-gray-600">
      Downcase letters followed by an optional region specifier in uppercase letters, separated by a dash. E.g. <span class="badge">fr</span> or <span class="badge">en-GB</span>.
    </p>
  </div>

  <%= f.submit class: "btn btn-primary mt-2" %>
<% end %>

app/views/rosetta/locales/_locale.html.erb
<tr>
  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
    <%= locale.name %>
  </td>
  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
    <span class="badge">
      <%= locale.code %>
    </span>
  </td>
  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
    <% if locale.default? %>
      <span class="pill">Default locale</span>
    <% end %>

    <% unless locale.default? %>
      <%= link_to "Manage", locale_translations_path(locale), class: "text-indigo-600 hover:text-indigo-900" %>
    <% end %>
  </td>
</tr>

app/views/rosetta/locales/index.html.erb
<div class="sm:flex sm:items-center">
  <div class="sm:flex-auto">
    <h1 class="text-base font-semibold leading-6 text-gray-900">Locales</h1>
    <p class="mt-2 text-sm text-gray-700">
      Manage the locales for your project.
    </p>
  </div>

  <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
    <%= link_to "Add locale", new_locale_path, class: "btn btn-primary", data: { action: "dialog#open" } %>
  </div>
</div>

<div class="mt-8">
  <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
    <table class="min-w-full divide-y divide-gray-300">
      <thead class="bg-gray-50">
        <tr>
          <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
          <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Key</th>
          <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
            <span class="sr-only">Manage</span>
          </th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200 bg-white">
        <%= render @locales %>
      </tbody>
    </table>
  </div>
</div>

app/views/rosetta/locales/new.html.erb
<%= within_modal do %>
  <%= modal_title "Add a new locale" %>
  <%= render "form", locale: @locale %>
<% end %>

app/views/rosetta/locales/translation_keys/index.html.erb
<div class="sm:flex sm:items-center">
  <div class="sm:flex-auto">
    <nav class="flex">
      <ol role="list" class="flex items-center space-x-2">
        <li>
          <%= link_to "Locales", locales_path, class: "text-base font-semibold leading-6 text-indigo-600 hover:text-indigo-900" %>
        </li>

        <li>
          <div class="flex items-center">
            <svg class="h-5 w-5 flex-shrink-0 text-gray-900" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
              <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
            </svg>

            <a href="#" class="ml-2 text-base font-semibold leading-6 text-gray-900" aria-current="page"><%= @locale.name %></a>
          </div>
        </li>
      </ol>
    </nav>

    <p class="mt-2 text-sm text-gray-700">
      Manage translations for this locale.
    </p>
  </div>
</div>

<div class="mt-8">
  <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
    <table class="min-w-full divide-y divide-gray-300">
      <thead class="bg-gray-50">
        <tr class="divide-x divide-gray-200">
          <th scope="col" class="w-1/2 py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Translation Key</th>
          <th scope="col" class="w-1/2 px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Translation</th>
        </tr>
      </thead>

      <tbody class="divide-y divide-gray-200 bg-white">
        <%= render collection: @translation_keys, partial: "rosetta/locales/translation_keys/translation_key" %>
      </tbody>
    </table>
  </div>
</div>

<div class="mt-4">
  <%== pagy_nav(@pagy) %>
</div>

app/views/rosetta/locales/translations/_navigation.html.erb
<div class="mt-6">
  <div class="border-b border-gray-200 flex justify-between items-center">
    <nav class="-mb-px flex space-x-8" aria-label="Tabs">
      <%= tab_link_to "All", locale_translations_path(@locale) %>

      <%= tab_link_to locale_translations_missing_index_path(@locale) do %>
        Missing
        <span class="ml-3 hidden md:inline-block rounded-full px-2.5 py-0.5 text-xs font-medium bg-gray-100 text-gray-900 group-[.active]:bg-indigo-100 group-[.active]:text-indigo-600">
          <%= Rosetta::TextEntry.where(locale: Rosetta::Locale.default_locale).missing_translation(@locale).size %>
        </span>
      <% end %>
    </nav>
  </div>
</div>

app/views/rosetta/locales/translations/_translation_key.html.erb
<tr class="divide-x divide-gray-200">
  <td class="py-4 pl-4 pr-3 text-sm text-gray-900 sm:pl-6">
    <%= translation_key.value %>
  </td>
  <td class="px-3 py-4 text-sm text-gray-900 group relative">
    <%= turbo_frame_tag dom_id(translation_key) do %>
      <%= translation_key.public_send("#{@locale.code}_translation")&.value %>

      <div class="hidden group-hover:flex absolute w-full h-full top-0 left-0 bg-indigo-50 bg-opacity-50 pr-4  items-center justify-end">
        <%= link_to "edit", edit_translation_key_translation_path(translation_key, locale_id: @locale.id), class: "text-indigo-600 hover:text-indigo-900 font-medium" %>
      </div>
    <% end %>
  </td>
</tr>

app/views/rosetta/locales/translations/index.html.erb
<div class="sm:flex sm:items-center">
  <div class="sm:flex-auto">
    <nav class="flex justify-between items-center">
      <ol role="list" class="flex items-center space-x-2">
        <li>
          <%= link_to "Locales", locales_path, class: "text-base font-semibold leading-6 text-indigo-600 hover:text-indigo-900" %>
        </li>

        <li>
          <div class="flex items-center">
            <svg class="h-5 w-5 flex-shrink-0 text-gray-900" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
              <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
            </svg>

            <div class="ml-2 text-base font-semibold leading-6 text-gray-900"><%= @locale.name %></div>
          </div>
        </li>
      </ol>

      <%= button_to "Deploy locale", locale_deploys_path(@locale), class: "btn btn-primary" %>
    </nav>

    <p class="mt-2 text-sm text-gray-700">
      Manage translations for this locale.
    </p>
  </div>
</div>

<%= render "rosetta/locales/translations/navigation" %>

<div class="mt-4">
  <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
    <table class="min-w-full divide-y divide-gray-300">
      <thead class="bg-gray-50">
        <tr class="divide-x divide-gray-200">
          <th scope="col" class="w-1/2 py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Text Entry</th>
          <th scope="col" class="w-1/2 px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Translation</th>
        </tr>
      </thead>

      <tbody class="divide-y divide-gray-200 bg-white">
        <%= render(
          collection: @text_entries,
          as: :text_entry,
          partial: "rosetta/text_entries/text_entry_with_translation") %>
      </tbody>
    </table>
  </div>
</div>

<div class="mt-4">
  <%== pagy_nav(@pagy) %>
</div>

app/views/rosetta/text_entries/_text_entry_with_translation.html.erb
<tr class="divide-x divide-gray-200">
  <td class="py-4 pl-4 pr-3 text-sm text-gray-900 sm:pl-6">
    <%= text_entry.content %>
  </td>
  <td class="px-3 py-4 text-sm text-gray-900 group relative">
    <%= turbo_frame_tag dom_id(text_entry) do %>
      <%= text_entry.content_in(@locale) %>

      <div class="hidden group-hover:flex absolute w-full h-full top-0 left-0 bg-indigo-50 bg-opacity-50 pr-4  items-center justify-end">
        <%= link_to "edit", edit_text_entry_translation_path(text_entry, locale_id: @locale.id), class: "text-indigo-600 hover:text-indigo-900 font-medium" %>
      </div>
    <% end %>
  </td>
</tr>

app/views/rosetta/translations/edit.html.erb
<%= turbo_frame_tag dom_id(@text_entry) do %>
  <%= form_with model: @text_entry, url: text_entry_translation_path(@text_entry), method: :patch, class: "relative" do |f| %>
    <%= hidden_field_tag :locale_id, @locale.id %>

    <div class="overflow-hidden rounded-lg shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-indigo-600">
      <%= f.label :"content_#{@locale.code}", "Translation", class: "sr-only" %>
      <%= f.text_area :"content_#{@locale.code}", row: 3, autofocus: true, placeholder: "Enter your translation", class: "block w-full resize-none border-0 bg-transparent py-1.5 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>

      <div class="py-2" aria-hidden="true">
        <div class="py-px">
          <div class="h-9"></div>
        </div>
      </div>
    </div>

    <div class="absolute inset-x-0 bottom-0 flex justify-end gap-2 py-2 pl-3 pr-2">
      <%= link_to "Discard", locale_translations_path(@locale), class: "btn btn-secondary" %>
      <%= f.submit "Save", class: "inline btn btn-primary" %>
    </div>
  <% end %>
<% end %>